# Lie Group and Lie Algebra from slambook

The notes from the chapter 3 of [slambook](https://github.com/gaoxiang12/slambook-en).

## What is a Group ?

A group $G$ is a set with a `well-defined` operation: $G = (A, \bullet)$ where the $A$ is the set and $\bullet$ is the operation. If $G$ is a group like defined above, it satisfies the following properties:

- closure: $\forall a_1, a_2 \in A; a_1 \bullet a_2 \in A$
- combination: $\forall a_1, a_2, a_3 \in A; (a_1 \bullet a_2) \bullet a_3 = a_1 \bullet (a_2 \bullet a_3)$
- unit element: $\exists a_0 \in A$ such that $\forall a \in A; a_0 \bullet a = a \bullet a_0 = a$
- inverse element: $\forall a \in A; \exists a^{-1} \in A$ such that $a \bullet a^{-1} = a_0$

## What is a Lie Group ?

Lie group is a group that is also a differentiable manifold. 
A differentiable manifold is a topological manifold with a globally defined differentiable structure.
A differentiable structure is defined using two elements: an atlas C and set V.

The atlas C is a set of mappings. The set V is the set of open subsets of $R^n$.
Each mapping $\phi \in C$ is a bijection, defined the following way: $\phi : m \to v$ where $m \in M$ and $v \in V$. M represents the manifold. 

In [21]:
# rotation matrix

import numpy as np

theta = 30
r1 = [1, 0, 0]
r2 = [0, np.cos(theta), -np.sin(theta)]
r3 = [0, np.sin(theta), np.cos(theta)]
rotmat = np.array([r1, r2, r3])
print(rotmat)
print(rotmat.dot(rotmat.T))
print(rotmat.T.dot(rotmat))

[[ 1.          0.          0.        ]
 [ 0.          0.15425145  0.98803162]
 [ 0.         -0.98803162  0.15425145]]
[[1.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.00000000e+00 1.28317219e-17]
 [0.00000000e+00 1.28317219e-17 1.00000000e+00]]
[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00 -1.28317219e-17]
 [ 0.00000000e+00 -1.28317219e-17  1.00000000e+00]]


## What is Lie Algebra ?

Lie algebra describes the local structure around the Lie Group's origin point. 
A Lie algebra is effectively the tangent space of a Lie Group. 
A Lie algebra $\mathbb{G}$ consists of $\mathbb{G} = (V, F, \circ)$ where $V$ is a set, $F$ is a scalar field and $\circ$ is a binary operation, often denoted as Lie bracket and used as $[x \circ y]$. 
If $\mathbb{G}$ is a Lie algebra then it satisfies the following properties:

- closure: $\forall X, Y \in V; [X \circ Y] \in V$
- bilinear composition: $\forall X, Y, Z \in V; a,b \in F$ we have: 
  $(aX + bY) \circ Z = a(X \circ Z) + b(Y \circ Z); Z \circ (aX + bY) = a(Z \circ X) + b(Z \circ Y)$
- reflexive: $\forall X \in V; [X \circ X] = 0$
- Jacobi identity: $\forall X,Y,Z \in V; [X \circ [Y \circ Z]] + [Z \circ [X \circ Y]] + [Y \circ [Z \circ X]] = 0$

From bilinear composition and reflexivity, we can also prove:
- anticommutativity: $[x \circ y] = -[y \circ x]$

An example of Lie algebra would be cross product in 3 dimensions. 
The signature would be: $(R^3, R, x)$. Let's verify this

In [20]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
z = np.array([7, 8, 9])
a = 1.2
b = 2.1
# bilinear composition

def check_bilinear_composition(x,y,z, fn):
    """
    $\forall X, Y, Z \in V; a,b \in F$ we have: 
    $(aX + bY) \circ Z = a(X \circ Z) + b(Y \circ Z); Z \circ (aX + bY) = a(Z \circ X) + b(Z \circ Y)$
    """
    f_1 = fn(a*x + b*y, z)
    f_2 = (a * fn(x,z)) + (b * fn(y, z))
    f_a = all(round(f_1[i], 3) == round(f_2[i], 3) for i in range(3))
    
    f_3 = fn(z, (a*x + b*y))
    f_4 = (a * fn(z, x)) + (b * fn(z, y))
    f_b = all(round(f_3[i], 3) == round(f_4[i], 3) for i in range(3))
    return f_a and f_b

print(check_bilinear_composition(x,y,z, np.cross))
# reflexive
def check_reflexive(x, fn):
    """ 
    $\forall X \in V; X \circ X = 0$
    """
    return all(f == 0 for f in fn(x, x))

print(check_reflexive(x, np.cross),
      check_reflexive(y, np.cross))

# jacobi identity
def check_jacobi_identity(x,y,z, fn):
    """
    Jacobi identity: $\forall X,Y,Z \in V; 
    (X \circ (Y \circ Z)) + (Z \circ (X \circ Y)) + (Y \circ (Z \circ X)) = 0$
    """
    fs = fn(x, fn(y,z)) + fn(z, fn(x,y)) + fn(y, fn(z,x))
    return all(f == 0 for f in fs)

print(check_jacobi_identity(x,y,z, np.cross))

True
True True
True


## Rotation matrix belongs to a Lie Group

3D rotation matrix constitutes a Lie Group called special orthogonal group (SO(3)). 
It is expressed like the following: $$SO(3) = \{ R \in \mathbb{R}^{3x3} | RR^T=I, det(R) = 1 \}$$

Its multiplication with its transpose is identity matrix and its determinant is 1. 
Its well-defined operator is matrix multiplication.
We can note for example that
$$(R_1 R_2) (R_1 R_2)^T = I$$

Distributing the transpose inside the paranthesis ([1]: p.54):
$$(R_1 R_2) R_2^T R_1^T = I$$

Following the associative law ([1]: p. 53):
$$R_1(R_2 R_2^T) R_1^T = I$$

The rest should be fairly clear: $R_2 R_2^T = I$:
$$R_1 I R_1^T = I$$
$$I = I$$

Notice that $R R^T=I \to R^T = R^{-1}$ due to inversion property of lie groups

## Transformation Matrix belongs to a Lie Group

The transformation matrix $T$ constitutes a special Euclidean Group (SE(3)).
It is expressed like the following:
$$SE(3) = \{T = \begin{pmatrix} R & t \\ 0 & 1 \end{pmatrix} \in \mathbb{R}^{4x4} | R \in SO(3), t \in R^3 \}$$

Basically the $R$ is the rotation matrix. The $t$ is the translation column vector. The last row is filled with 0s until the last column, which is filled with 1.
The well-defined operator for the $SE(3)$ is matrix multiplication.
This can be seen from:
$$T_1 T_2 = \begin{pmatrix}
R_1 & t_1 \\
0^T & 1 
\end{pmatrix} 
\begin{pmatrix}
R_2 & t_2
0^T & 1
\end{pmatrix}
= \begin{pmatrix}
R_1 R_2 & R_1 t_2 + t_1 \\
0^T & 1
\end{pmatrix}
$$

Since $R_1 R_2 \in SO(3)$ and $R_1 t_2 + t_1 \in R^{3x3}$, we can claim that $T \in SE(3)$ and forms a Lie group

## Derivative of Rotation Matrix produces Lie Algebra of SO(3)

Given rotation matrix $R$, we know that: $$RR^{T} = R^{T}R = I$$

Now the camera changes its rotation over time, so we can rewrite this relation as:$$R(t)R(t)^{T}=I$$
We want to see, how rotation behaves as it changes over time. Mathematically, we need to derive $R$ for $t$, meaning that we are looking for $R'(t) = \frac{R(t + h) - R(t)}{h}$. Given the former relation to identity matrix, we can proceed as the following: 

if $$f = R(t)R(t)^{T} = I$$, 
then $$f' = 0$$ since identity matrix is constant and the derivative of a constant is 0.

Then, we can expand the derivative $f' = 0$ as the following using the product rule of derivation:
$$R'(t)R(t)^{T} + R(t)R'(t)^{T} = 0$$

Move the second term to right: $$R'(t)R(t)^{T} = -(R(t)R'(t)^{T})$$

Notice that we have the following structure: $AB^{T} = -BA^{T}$
The right side of the equation can be expressed like the following under the transpose relation:
$$AB^{T} = -(AB^{T})^{T}$$

(Remember that $(AB)^{T} = B^{T} A^{T}$ the order is reversed)

Then the resulting equation is: $$R'(t)R(t)^{T} = - (R'(t)R(t)^{T})^T$$

This shows that $R'(t)R(t)^{T}$ is skew symmetric, because the definition of skew-symmetric matrix implies that $A^T=-A$

Now if $R'(t)R(t)^T$ is skew-symmetric matrix, then there is a unique 3d vector that represents its coefficients. Let's call that vector $\phi(t) \in R^3$. 

Let $\lambda$ be the map that transforms $\phi$ to matrix, $\lambda: R^3 \to R^{3x3}$.
Then given: $$ R'(t)R(t)^{T}=\lambda(\phi(t))$$
we can multiply both sides with $R(t)$ as in: $$R'(t)R(t)^T R(t) = \lambda(\phi(t)) R(t)$$

This would give $$R'(t) I = \lambda(\phi(t))R(t)$$

which is the same as $$R'(t) = \lambda(\phi(t)) R(t)$$

Here is the catch: Since $\lambda(\phi(t))$ gives the derivative of $R(t)$ when multiplied, then $\lambda(\phi)$ or simply $\phi$ is the tangent space of an arbitrary rotation.
In Lie Group terms, it is the tangent space near the origin of special orthogonal group 3 (SO(3)). Hence, it is the lie algebra that corresponds to lie group SO(3).

## Lie Algebra of SE(3)

The lie algebra $\mathbb{se}(3)$ of $SE(3)$ group is formally defined as:
$$\mathbb{se}(3) = \{ \xi = [\rho, \phi] \in \mathbb{R}^{6}: \rho \in \mathbb{R}, \phi \in \mathbb{so}(3) \} = (\mathbb{R}^{6}, \mathbb{R}, \diamond)$$

Additionally, like the $\lambda$ function in $\mathbb{so}(3)$, we have $\gamma: \mathbb{R}^6 \to \mathbb{R}^{4x4}$ function.
The matrix produced by the $\gamma$ function is slightly different than the $\lambda$ function, but it serves to the same purpose, promote a given vector to matrix.

The $\gamma$ function produces the following matrix upon application to $\xi$:
$$\gamma(\xi) = \begin{pmatrix} \lambda(\phi) & \rho \\ 0 & 0 \end{pmatrix}$$

Notice that the matrix produced by the $\gamma$ function is no longer a skew-symmetric matrix.

The binary operator $\diamond$ for $\mathbb{se}(3)$ is defined in similar fashion to $\square$ of $\mathbb{so}(3)$:
$$\xi_1 \diamond \xi_2 = \Gamma(\gamma(\xi_1) \gamma(\xi_2) - \gamma(\xi_2)\gamma(\xi_1))$$

where $\Gamma$ transforms the matrix $\gamma(\xi)$ back into a vector.

## exp Function

Exponential function ties lie algebra to lie group.

The exponential function applied to matrix $A \in R^{MxM}$ is defined as:
$$\exp(A) = I + A + \frac{1}{2!} A^2 + \frac{1}{3!} A^3 + \dots = \sum_{n = 0}^{\infty} \frac{1}{n!} A^n$$

The logarithm can also be applied to matrix $A$:
$$ln(A) = \sum_{n=1}^{\infty} \frac{(-1)^{n-1}}{n} (A - I)^n$$

## Going back and forth between SO(3) and its algebra

Given $R(t)$ and its derivative we can expand the $R(t)$ into taylor series to see if we can obtain $R(t)$ from $\phi$ itself.

We know that at $t = 0 = t_0$ the rotation matrix is equal to identity, $R(t_0 = 0) = I$. From here, the taylor expansion of the function until the first order derivative $R'(t_0)$ would be:
$$R(t) \approx R(t_0) + \frac{R'(t_0)(t-t_0)}{1!}$$

This reduces to $$R(t) \approx I + \lambda(\phi(t_0)) R(t_0) (t)$$
Since $R(t_0)=I$, we get $$R(t) \approx I + \lambda(\phi(t_0)) I (t)$$
Hence we are left with: $$R(t) \approx I + \lambda(\phi(t_0))(t)$$

This last serie resembles awfully a lot to that of exponential function: $e^x \approx \sum_{n=0}^{\infty} \frac{x^n}{n!}$, where the first terms would be $1 + x + \frac{x^2}{2!} + \frac{x^3}{3!}$.

If we consider $x = \lambda(\phi(t_0))(t)$ we can see that $R(t) \approx \exp(x)$ around $t_0$.

Now, we know that $\lambda(\phi(t))$ is a skew-symmetric matrix. Would it loose this property if we multiply it by a scalar like $t$ ? No, so $\lambda(\phi(t_0))(t)$ is also a skew-symmetric matrix.  

Hence rotation matrix is tied to two skew symmetric matrices: 
- Its derived with a skew-symmetric matrix as in $R'(t) = \lambda(\phi(t)) R(t)$
- It is approximated with a skew-symmetric matrix as in $R(t) \approx \exp(\lambda(\phi(t_0))(t))$

From this last relation we can also estimate that: $\lambda(\phi(t_0))(t) \approx ln(R(t))$

Then formally lie algebra $\mathbb{so}(3)$ of $SO(3)$ is defined as
$$\mathbb{so}(3) = \{ \phi \in \mathbb{R}^3 or \lambda(\phi) \in \mathbb{R}^{3x3} \} = (\mathbb{R}^3, \mathbb{R}, \square)$$
where the $\square$ binary operator is defined as
$$\phi_1 \square \phi_2 = \Lambda(\lambda(\phi_1) \lambda(\phi_2) - \lambda(\phi_2) \lambda(\phi_1)$$

where $\Lambda: \mathbb{R}^{3x3} \to \mathbb{R}^3$ meaning that it transforms the skew-symmetric matrix back to its vector representation 

We can also define the axis-angle form with exp. 
Let $\Phi \in \mathbb{R}^3$ be an lie algebra defined as $\Phi = \phi \theta$ where $\theta = ||\Phi|| \in \mathbb{R}$ is the norm/angle and $\phi = \frac{\Phi}{\theta} \in \mathbb{R}^3$ is the axis of rotation.

The $\exp(\lambda(\Phi))$ can be computed using axis-angle representation.
First let's move the scalar angle from skew operator:
$$\exp(\lambda(\Phi)) = 
\exp(\theta \lambda(\phi))$$

Now we expand the expression:
$$\exp(\lambda(\Phi)) = 
I + \theta \lambda(\phi) + \frac{1}{2!} \theta^2 \lambda(\phi)^2 + \frac{1}{3!} \theta^3 \lambda(\phi)^3 +\frac{1}{4!} \theta^4 \lambda(\phi)^4+ \dots$$

Before we advance, we need to introduce 2 other equalities with respect to axis $\phi$.

Here is the first one:
$\lambda(\phi)^2 = \phi \phi^T - I$

The proof is simple assuming
$\phi = [p_1, p_2, p_3]$:

$$\begin{pmatrix}
0 & -p_3 & p_2 \\
p_3 & 0 & -p_1 \\
-p_2 & p_1 & 0
\end{pmatrix}
\begin{pmatrix}
0 & -p_3 & p_2 \\
p_3 & 0 & -p_1 \\
-p_2 & p_1 & 0
\end{pmatrix} 
= \phi \phi^T - I$$

Now let's do the multiplication:
$$
\begin{pmatrix}
0 * 0 + p_3 * -p_3 + -p_2 * p_2 & -p_3 * 0 + 0 * -p_3 + p_1 * p_2 & p_2 * 0 + -p_1 * p_3 + 0 * p_2 \\
p_1 p_2 & -p_1^2 - p_3^2 & p_2 p_3 \\
p_1 p_3 & p_2 p_3 & -p_1^2 -p_2^2
\end{pmatrix} =
\begin{pmatrix}
-p_3^2 - p_2^2 & p_1 p_2 & -p_1 p_3\\
p_1 p_2 & -p_1^2 - p_3^2 & p_2 p_3 \\
p_1 p_3 & p_2 p_3 & -p_1^2 -p_2^2
\end{pmatrix} = \phi \phi^T - I
$$

Expanding the right side:
$$
\begin{pmatrix}
-p_3^2 - p_2^2 & p_1 p_2 & -p_1 p_3\\
p_1 p_2 & -p_1^2 - p_3^2 & p_2 p_3 \\
p_1 p_3 & p_2 p_3 & -p_1^2 -p_2^2
\end{pmatrix} =
\begin{pmatrix}
p_1 * p_1 & p_1 * p_2 & p_1 * p_3 \\
p_2 * p_1 & p_2 * p_2 & p_2 * p_3 \\
p_3 * p_1 & p_3 * p_2 & p_3 * p_3
\end{pmatrix} - I
$$

By now the similarity should be visible:
$$
\begin{pmatrix}
-p_3^2 - p_2^2 & p_1 p_2 & -p_1 p_3\\
p_1 p_2 & -p_1^2 - p_3^2 & p_2 p_3 \\
p_1 p_3 & p_2 p_3 & -p_1^2 -p_2^2
\end{pmatrix} =
\begin{pmatrix}
p_1^2& p_1 p_2 & p_1 p_3 \\
p_2 p_1 & p_2^2& p_2 p_3 \\
p_3 p_1 & p_3 p_2 & p_3^2
\end{pmatrix} - I
$$

Incorporating the identity as well:
$$
\begin{pmatrix}
-p_3^2 - p_2^2 & p_1 p_2 & -p_1 p_3\\
p_1 p_2 & -p_1^2 - p_3^2 & p_2 p_3 \\
p_1 p_3 & p_2 p_3 & -p_1^2 -p_2^2
\end{pmatrix} =
\begin{pmatrix}
p_1^2 - 1 & p_1 p_2 & p_1 p_3 \\
p_2 p_1 & p_2^2 - 1 & p_2 p_3 \\
p_3 p_1 & p_3 p_2 & p_3^2 - 1
\end{pmatrix}
$$

Since the axis vector is a unit vector, meaning that $1 = \sqrt{p_1^2 + p_2^2 + p_3^2}$ hence
$1 = p_1^2 + p_2^2 + p_3^2$

With this equation in mind, it is apparent that:
$$p_1^2 - 1 = -p_3^2 - p_2^2$$
$$p_2^2 - 1 = -p_3^2 - p_1^2$$
$$p_3^2 - 1 = -p_1^2 - p_2^2$$

This concludes the proof.

Here is the second one:
$\lambda(\phi)^3 = -\lambda(\phi)$

First lets expand the expression:
$$\lambda(\phi) \lambda(\phi)^2 = -\lambda(\phi)$$

From above we know that:
$$\lambda(\phi) (\phi \phi^T - I) = -\lambda(\phi)$$

Since matrix multiplication is distributive:
$$\lambda(\phi) \phi \phi^T - \lambda(\phi) = -\lambda(\phi)$$

Let's expand the $\lambda(\phi) \phi$:
$$
\begin{pmatrix}
0 & -p_3 & p_2 \\
p_3 & 0 & -p_1 \\
-p_2 & p_1 & 0
\end{pmatrix} [p_1, p_2, p_3]
$$

Now we do the multiplication:
$$
\begin{pmatrix}
0 * p_1 + -p_3 * p_2 + p_2 * p_3 \\
p_3 p_1 + p_2 + -p_1 p_3 \\
-p_2 p_1 + p_1 p_2 + 0
\end{pmatrix} = 0
$$
Then our initial expression becomes:
$$0 * \phi^T - \lambda(\phi) = -\lambda(\phi)$$

Which gives us $- \lambda(\phi) = -\lambda(\phi)$

This concludes the second proof.

Going back to our original expression:
$$\exp(\lambda(\Phi)) = 
I + \theta \lambda(\phi) + \frac{1}{2!} \theta^2 \lambda(\phi)^2 + \frac{1}{3!} \theta^3 \lambda(\phi)^3 +\frac{1}{4!} \theta^4 \lambda(\phi)^4+ \dots$$

We can now substitute some expressions:
$$\exp(\lambda(\Phi)) = 
I + \theta \lambda(\phi) + \frac{1}{2!} \theta^2 \lambda(\phi)^2 + \frac{1}{3!} \theta^3 (-1*\lambda(\phi)) + \frac{1}{4!} \theta^4 (-1*\lambda(\phi) \lambda(\phi)) 
+ \frac{1}{5!} \theta^5 (-1*\lambda(\phi) \lambda(\phi) \lambda(\phi)) 
+ \dots$$

From here, it should be apparent that odd fractions like $\frac{1}{3}$ and $\frac{1}{5}$ would have alternating signs with $\lambda(\phi)$

We can reexpress the odd fractions like the following way then:
$$\exp(\lambda(\Phi)) = 
I + \frac{1}{2!} \theta^2 \lambda(\phi)^2 + \frac{1}{4!} \theta^4 (-1*\lambda(\phi) \lambda(\phi)) 
+ \dots +
(\theta - \frac{1}{3!} \theta^3 + \frac{1}{5!} \theta^5 - \dots) \lambda(\phi) 
$$

In [5]:
import numpy as np

a = np.array([[1], [2], [3]])
print(a @ a.T)

[[1 2 3]
 [2 4 6]
 [3 6 9]]


## Going back and forth between SE(3) and its algebra

As in the $SO(3)$ case the passage from $\mathbb{se}(3)$ to $SE(3)$ is done through $exp$ function:
$$\exp(\gamma(\xi)) = \begin{pmatrix} \exp(\lambda(\phi)) & J \rho \\ 0 & 1 \end{pmatrix}$$
where $J$ is the jacobian first order derivative matrix defined as:
$$J = \frac{\sin(\theta)}{\theta} I + (1 - \frac{\sin(\theta)}{\theta}) aa^T + \frac{1 - \cos(\theta)}{\theta} a\hat{}$$
where $\theta$ is the length and $a$ is the unit-length direction vector of $\phi$, so that $\phi=\theta a$

The $\exp(\lambda(\phi))$ is simply the rotation matrix $R$.
The $J$ depends on $\phi$ as well.
If $J$ depends on $\phi$ we can find the $\rho$ simply by solving $J\rho = t$ using LU decomposition.
We assume that $t$ is available from the transformation matrix $T$.

Going from $SE(3)$ to $\mathbb{se}(3)$ is easier:
We had already seen $J\rho = t$, we only need to see how to reach to $\phi$ and consequently $\theta, a$ due to $\phi=\theta a$

The $\theta$ is dependent on the trace of rotation: $\theta = \arccos(\frac{trace(R) - 1}{2})$
The $a$ is dependent on $R a = a$ meaning that $a$ is the eigenvector of $R$ when $R$'s eigenvalue is 1.

## SO(3) and SE(3) Summary

- Lie group: $SO(3)$, its algebra $\mathbb{so}(3)$
  - $SO(3) = (R \in \mathbb{3x3}, \star)$ where $\star$ represents matrix multiplication and $RR^T = I$ and $det(R) = 1$
  - $\mathbb{so}(3) = (\phi \in R^{3}, R, \square)$ where $\square$ represents a binary operator as explained above.
  - Conversion from $SO(3)$ to $\mathbb{so}(3)$ happens the following way:
    - Assume $\phi = \theta \alpha$ where $\alpha$ is a unit length direction vector ($\alpha \in \mathbb{R}^3$) and $\theta$ is length ($\theta \in \mathbb{R}$). 
      Then $\theta = \arccos(\frac{trace(R) - 1}{2})$ and $R\alpha = \alpha$
  - Conversion from $\mathbb{so}(3)$ to $SO(3)$ happens the following way:
    - Assume $\phi = \theta \alpha$ where $\alpha$ is a unit length direction vector ($\alpha \in \mathbb{R}^3$) and $\theta$ is length ($\theta \in \mathbb{R}$).
      Then $\exp(\theta \lambda(\alpha)) = \cos(\theta)I+(1-\cos(\theta))\alpha \alpha^T+\sin(\theta)\lambda(\alpha)$ where $\lambda: \mathbb{R}^3 \to \mathbb{R}^{3x3}$
      
- Lie group: $SE(3)$, its algebra $\mathbb{se}(3)$
  - $SE(3) = (T = \begin{pmatrix}R \in \mathbb{R}^{3x3} & t \in \mathbb{R}^3 \\ 0 & 1\end{pmatrix} \in \mathbb{R}^{4x4}, \star)$ where $\star$ represents matrix multiplication.
  - $\mathbb{se}(3) = (\xi = [\rho \in \mathbb{R}^3, \phi \in \mathbb{R}^3] \in \mathbb{R}^{6}, \mathbb{R}, \diamond)$ where the binary operator $\diamond$ for $\mathbb{se}(3)$ is defined in similar fashion to $\square$ of $\mathbb{so}(3)$
  - Conversion from $SE(3)$ to $\mathbb{se}(3)$ happens the following way:
    - Assume $\phi = \theta \alpha$ where $\alpha$ is a unit length direction vector ($\alpha \in \mathbb{R}^3$) and $\theta$ is length ($\theta \in \mathbb{R}$). 
      Then $\theta = \arccos(\frac{trace(R) - 1}{2})$ and $R\alpha = \alpha$, $t=J\rho$, and $J=\frac{\sin(\theta)}{\theta} I + (1 - \frac{\sin(\theta)}{\theta}) \alpha\alpha^T + \frac{1 - \cos(\theta)}{\theta} \alpha\hat{}$
  - Conversion from $\mathbb{se}(3)$ to $SE(3)$ happens the following way:
    - $\exp(\gamma(\xi)) = \begin{pmatrix} \exp(\lambda(\phi)) & J\rho \\ 0 & 1\end{pmatrix}$
    
Basically we go to algebra to group with $\exp$ and group to algebra with $\ln$

## Derivative of SO(3) and SE(3)

There is an important motivation to compute the derivative of the $SO(3)$ and $SE(3)$: optimization.
Given an observation $z = Tp + w$ where $z \in \mathbb{R}^2$ is the observed point, $T$ is the transformation matrix, $p$ is the point in world coordinates, and $w$ is gaussian noise, we want to minimize the effect of the error.
Loss can be formulated as $f_{loss} = z - Tp$.
We are looking for the minimum value of this function. 
One way to do it would be setting its derivative to 0: $f'_{loss} = 0$
Now, what's its argument ? 
The target variable for this process is $T$, as we want to have best transformation matrix that gives
the error free result.

Here is the catch, we want to take the derivative of $T$, taking it in matrix form involves taking a lot of derivatives, but if we take $T$'s derivative in $SE(3)$ where we can describe infinitesmal change with a vector through conversion to $\mathbb{se}(3)$, we can get away with a much simpler setting.

### Derivative of SO(3) through Left Perturbation

Let $\nabla R \in \mathbb{R}^{3x3}$ be a perturbation of $SO(3) = R \in \mathbb{R}^{3x3}$ through matrix multiplication as in $\nabla R \star R$. 

Assuming the $\mathbb{so}(3)$ for $\nabla R$ to be $\kappa$, we are looking for derivative of $R$ in function $Rp$.
This can be formulated as 
$$\frac{\partial(Rp)}{\nabla R} = \lim_{\kappa \to 0} \frac{\exp(\lambda(\kappa)) \exp(\lambda(\phi))p - \exp(\lambda(\phi))p}{\kappa}$$
Notice that we are converting the $SO(3)$s into $\mathbb{so}(3)$ directly through $\exp$.
The first term $\exp(\lambda(\kappa))$ expands into $(I + \lambda(\kappa))$ by approximating it with Taylor series.
Since matrix multiplication distributes over the addition, we have the following situation:
$$ = \lim_{\kappa \to 0} \frac{(I+\lambda(\kappa))\exp(\lambda(\phi))p - \exp(\lambda(\phi))p}{\kappa}$$
$$ = \lim_{\kappa \to 0} \frac{\exp(\lambda(\phi))p+\lambda(\kappa)\exp(\lambda(\phi))p - \exp(\lambda(\phi))p}{\kappa}$$
consequently the same terms cancel out:
$$ = \lim_{\kappa \to 0} \frac{\lambda(\kappa)\exp(\lambda(\phi))p}{\kappa}$$
Let's replace the $\exp(\lambda(\phi))$ with its $SO(3)$ form:
$$ = \lim_{\kappa \to 0} \frac{\lambda(\kappa)Rp}{\kappa}$$
Now remember that $Rp$ results in $Rp \in \mathbb{R}^3$, hence $\lambda(\kappa)Rp$ is essentially cross product of 2 3d vectors, since cross products can also be expressed using a skew-symmetric matrix.

$$ = \lim_{\kappa \to 0} \frac{\lambda(\kappa) \times Rp}{\kappa}$$

Now, from linear algebra we know that $a \times b = -b \times a$, hence:
$$ = \lim_{\kappa \to 0} \frac{-Rp \times \lambda(\kappa)}{\kappa}$$
Again from basic linear algebra we know that $a \times b = \lambda(a) \dot b$.
Basically we can transform the first term into skew symmetric matrix and do an inner product instead. 
This transforms our equation into:
$$ = \lim_{\kappa \to 0} \frac{\lambda(-Rp) \kappa}{\kappa}$$
$\kappa$s cancel out:
$$ = \lim_{\kappa \to 0} \lambda(-Rp)$$
Since there is no $\kappa$, there is no need for the $\lim$ anymore, so our final equation is:
$$\frac{\partial(Rp)}{\nabla R} = \lambda(-Rp)$$

### Derivative of SE(3) through Left Perturbation

Let $\nabla T \in \mathbb{R}^{4x4}$ be a perturbation of $SE(3) = T \in \mathbb{R}^{4x4}$ through matrix multiplication as in $\nabla T \star T$. 

Assuming the $\mathbb{se}(3)$ for $\nabla T$ to be $\beta$, we are looking for derivative of $T$ in function $Tp$.
This can be formulated as 
$$\frac{\partial(Tp)}{\nabla T} = \lim_{\beta \to 0} \frac{\exp(\gamma(\beta)) \exp(\gamma(\xi))p - \exp(\gamma(\xi))p}{\beta}$$
Notice that we are converting the $SE(3)$s into $\mathbb{se}(3)$ directly through $\exp$.

The first term $\exp(\gamma(\beta))$ expands into $(I + \gamma(\beta))$ by approximating it with Taylor series.
Since matrix multiplication distributes over the addition, we have the following situation:
$$ = \lim_{\beta \to 0} \frac{(I+\gamma(\beta))\exp(\gamma(\xi))p - \exp(\gamma(\xi))p}{\beta}$$
$$ = \lim_{\beta \to 0} \frac{\exp(\gamma(\xi))p+\gamma(\beta)\exp(\gamma(\xi))p - \exp(\gamma(\xi))p}{\beta}$$
consequently the same terms cancel out:
$$ = \lim_{\beta \to 0} \frac{\gamma(\beta)\exp(\gamma(\xi))p}{\beta}$$

Now let's substitute the $\mathbb{se}(3)$ forms with their $SE(3)$ equivalents:
$$ = \lim_{\beta \to 0} \frac{\begin{pmatrix} \lambda(\phi) & \rho \\ 0 & 0 \end{pmatrix} \begin{pmatrix} Rp + t \\ 1\end{pmatrix}}{\beta}$$

We do the multiplication:
$$ = \lim_{\beta \to 0} \frac{\begin{pmatrix} \lambda(\phi) (Rp + t) + \rho \\ 0  \end{pmatrix}}{\beta}$$

Now $\beta$ is essentially a vector $\beta = [\rho, \phi] \in \mathbb{R}^3$.
$\phi$ is intentional, it represents the algebra of rotation.
When we substitute the $\beta$ with its vector form, we get:

$$ = \lim_{\beta \to 0} \frac{\begin{pmatrix} \lambda(\phi) (Rp + t) + \rho \\ 0 \end{pmatrix}}{[\rho, \phi]}$$
Notice that this is actually a series of a vector to vector derivations:
$\eta = \lambda(\phi) (Rp + t) + \rho$
$$ = \lim_{\beta \to 0} \begin{pmatrix} \frac{\partial(\eta)}{\rho} & \frac{\partial(\eta)}{\phi} \\ \frac{\partial(0)}{\rho} & \frac{\partial(0)}{\phi} \end{pmatrix}$$

The bottom row is composed of zeros:
$$ = \lim_{\beta \to 0} \begin{pmatrix} \frac{\partial(\eta)}{\rho} & \frac{\partial(\eta)}{\phi} \\ 0 & 0 \end{pmatrix}$$

The $\frac{\partial(\eta)}{\rho}$ is $I$ because $\rho$'s coefficient in $\eta$ is 1.
The $\frac{\partial(\eta)}{\phi}$ follows a very similar logic to $SO(3)$ case. 
We rewrite the $\eta$ like the following:
$$\eta = \phi \times (Rp + t) + \rho$$
We switch the places in cross product:
$$\eta = -(Rp + t) \times \phi + \rho$$
Then we convert the cross product into dot product again:
$$\eta = \lambda(-(Rp + t))\phi + \rho$$
Once we have defined the $\eta$ in this form the partial derivative with respect to $\phi$ reduces to $\phi$'s coefficient in $\eta$
$$\frac{\partial(\eta)}{\phi} = \lambda(-(Rp+t))$$

Hence the final form of the equation leads to the following expression:
$$\frac{\partial(Tp)}{\nabla T} = \begin{pmatrix} I & \lambda(-(Rp+t)) \\ 0 & 0 \end{pmatrix}$$

This is a 4x6 matrix where $I \in \mathbb{R}^{3x3}$ and $\lambda(-(Rp+t)) \in \mathbb{R}^{3x3}$

# References

[1] S. Lang, Introduction to Linear Algebra, 2nd ed. in Undergraduate Texts In Mathematics. New Haven: Springer, 1986.

[2] A. Baker, Matrix groups: an introduction to Lie group theory, 3. print. in Springer undergraduate mathematics series. London Berlin Heidelberg: Springer, 2006.

[3] T. D. Barfoot, State Estimation for Robotics, 1st ed. Cambridge University Press, 2017. doi: 10.1017/9781316671528.
